golangci-lint実行時の修正対応
msh5/boy pull request #18
Opened 2020-05-05 09:24 UTC by ShintaNakama

## 変更内容
- make lint (golangci-lint run) 実行時に出力されるエラーに対して修正しました。

- xerrors pkgを使いました。
- 参考にした記事(https://qiita.com/sonatard/items/9c9faf79ac03c20f4ae1)

- ただ1点私のローカルだと消えないエラーがあります。
- xerrorsをimportしたとこがエラーになっていて、エラー内容をそのまま訳すると、`対象のファイルが -local github.com/msh5/boy で `goimports`-ed されていません。` となっており、goimportsを実行してもらうことになるのかなと思っております。
```
18:18 ~/go/src/github.com/ShintaNakama/boy $ make lint                                                                                                                                                                    [fix/golangci-lint]
golangci-lint run
ifadapter/controller/exec_controller.go:3: File is not `goimports`-ed with -local github.com/msh5/boy (goimports)
import (
ifadapter/controller/show_controller.go:3: File is not `goimports`-ed with -local github.com/msh5/boy (goimports)
import (
interface/persistence/gist_entry_persistence.go:5: File is not `goimports`-ed with -local github.com/msh5/boy (goimports)

make: *** [lint] Error 1
```

2020-05-06 13:15 UTC, msh5 requested changes

2020-05-06 13:15 UTC, msh5 commented on app/interactor/snippet_exec_interactor.go
> +}
Please fix as following:

```suggestion
func (e *execNoFileError) Error() string {
	return "no files in gist entry"
}
```

Not only this error, but also all of errors as well.

2020-05-06 13:15 UTC, msh5 commented on ifadapter/controller/reference_parser.go
> +	gitHubRLSegmentCount               = 4
Could you split const block with referenceType definitions ?

2020-05-06 13:15 UTC, msh5 commented on app/interactor/snippet_show_interactor.go
> +}
This is duplicate code with `execNoFileError`, I want to avoid that.

2020-05-06 13:15 UTC, msh5 commented on ifadapter/controller/show_controller.go
> +type showUnknownReferenceTypeError struct {
Duplicated code with `execUnknownReferenceTypeError`.

2020-05-06 13:56 UTC, ShintaNakama commented on app/interactor/snippet_exec_interactor.go
> +}
かしこまりました。修正します。
局所的に使用するエラーなので、エラー文を変更できるようにする必要が無いということですね。

2020-05-07 08:12 UTC, msh5 requested changes
Enough good, but please one more tiny fix.

2020-05-07 08:12 UTC, msh5 commented on ifadapter/controller/controller_error.go
> +type unKnownReferenceTypeError struct{}
"unknown" is one word, no need to split.

```suggestion
type unknownReferenceTypeError struct{}
```

2020-05-07 08:12 UTC, msh5 commented on ifadapter/controller/controller_error.go
> +type unExpectedReferenceError struct{}
"unexpected" is one word, no need to split.

2020-05-07 13:10 UTC, msh5 approved these changes
LGTM 🍏

2020-05-07 14:00 UTC, ShintaNakama commented on ifadapter/controller/controller_error.go
> +type unKnownReferenceTypeError struct{}
Corrected.

2020-05-07 14:01 UTC, merged